.PHONY: all
all: name fifty absolute random free_choice voltage namecount fiftytally.cpp

name: name.cpp
	g++ -o name name.cpp

fifty: fifty.cpp
	g++ -o fifty fifty.cpp

absolute:
	g++ -o absolute absolute.cpp

random:
	g++ -o random random.cpp

free_choice:
	g++ -o free_choice free_choice.cpp

voltage:
	g++ -o voltage voltage.cpp

namecount:
	g++ -o namecount namecount.cpp

fiftytally: fiftytally.cpp
	g++ -o fiftytally fiftytally.cpp
