.PHONY: all
all: ticket ticket_discount did_i_fail how_low guess guess_loop

ticket: ticket_discount.cpp
	g++ -o ticket_discount		 ticket_discount.cpp

did_i_fail: did_i_fail.cpp
	g++ -o did_i_fail did_i_fail.cpp

how_low: how_low.cpp
	g++ -o how_low how_low.cpp

guess: guess.cpp
	g++ -o guess guess.cpp

guess_loop: guess_loop.cpp
	g++ -o guess_loop guess_loop.cpp
